listeners:
- query_port: 25577
  motd: '\u00a7l \u00a79                   \u30fb\u304a\u3076\u3058\u3047\u3063\u3066\u3043\u751f\u6d3b\u9bd6\u30fb\u00a7r\n\u00a7l \u00a7r                       \u00a7ka \u00a7e\u30b9\u30c6\u30fc\u30b8\u30f3\u30b0 \u00a7r\u00a7ka'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 3
  tab_size: 60
  force_default_server: false
disabled_commands:
- disabledcommandhere
network_compression_threshold: 256
groups:
  md_5:
  - admin
connection_throttle: 4000
connection_throttle_limit: 3
stats: 87c80ac8-4226-478b-8635-c67e86c47147
online_mode: true
forge_support: false
inject_commands: false
timeout: 30000
log_initial_handler_connections: true
player_limit: -1
prevent_proxy_connections: false
server_connect_timeout: 5000
remote_ping_timeout: 5000
remote_ping_cache: 5000
log_pings: true
ip_forward: true
favicon: server-icon.png
servers:
  lobby:
    address: lobby-paper-server-service-stg:25565
    restricted: false
  survival:
    address: survival-paper-server-service-stg:25565
    restricted: false