listeners:
- host: 0.0.0.0:25577
  motd: 'Staging Minecraft Network - Backend Offline'
  priorities: []
  proxy_protocol: false
  force_default_server: false
  tab_list: GLOBAL_PING
servers: {}
online_mode: true
ip_forward: true
connection_throttle: 4000
connection_throttle_limit: 3
timeout: 30000
remote_ping_timeout: 5000
remote_ping_cache: 5000