listeners:
- host: 0.0.0.0:25577
  motd: 'Staging Minecraft Network'
  priorities:
  - lobby
  proxy_protocol: false
servers:
  lobby:
    address: lobby-paper-server-service-stg:25565
    restricted: false
  survival:
    address: survival-paper-server-service-stg:25565
    restricted: false
online_mode: true
ip_forward: true