apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - cloudflare-config.yaml
  - minio-secret.yaml

nameSuffix: -stg

namespace: objectt-minecraft-stg

patchesStrategicMerge:
- paper-patch.yaml
- loadbalancer-patch.yaml
- minio-sync-env-patch.yaml

configMapGenerator:
- name: bungeecord-config
  files:
  - bungeecord-config.yaml
  - server-icon.png
- name: paper-config  
  files:
  - spigot.yml

generatorOptions:
  disableNameSuffixHash: true