apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby-paper-server
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
              - key: kubernetes.io/hostname
                operator: In
                values:
                - "k8s-wk-1"
                - "k8s-wk-2"
                - "k8s-wk-3"
      initContainers:
      - name: plugin-downloader
        image: minio/mc:RELEASE.2025-07-21T05-28-08Z-cpuv1
        env:
        - name: MINIO_ENDPOINT
          value: "minio-service-stg:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: root-user
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: root-password
        - name: BUCKET_NAME
          value: "plugins"
        - name: MC_CONFIG_DIR
          value: "/tmp/.mc"
        volumeMounts:
        - name: plugins-volume
          mountPath: /plugins
        - name: minio-config
          mountPath: /tmp/.mc
        command:
        - sh
        - -c
        - |
          echo "Downloading plugins from MinIO..."
          mkdir -p /plugins
          
          # Reset existing jar files in plugins directory
          echo "Resetting existing jar files..."
          rm -f /plugins/*.jar
          
          # Configure MinIO connection
          mc alias set minio http://${MINIO_ENDPOINT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}
          
          # List buckets to verify connection
          echo "Available buckets:"
          mc ls minio/
          
          # Download all plugins from bucket
          echo "Downloading from bucket: ${BUCKET_NAME}"
          mc cp --recursive minio/${BUCKET_NAME}/ /plugins/ || echo "No files in bucket or bucket not found"
          
          echo "Plugin download completed"
          ls -la /plugins
      containers:
      - name: paper
        env:
        - name: WHITELIST
          value: "naoido,kurazuuuuuu"
        - name: MEMORY
          value: "1G"
        - name: COPY_PLUGINS_SRC
          value: "/plugins"
        volumeMounts:
        - name: plugins-volume
          mountPath: /plugins
      volumes:
      - name: plugins-volume
        emptyDir: {}
      - name: minio-config
        emptyDir: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: survival-paper-server
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
              - key: kubernetes.io/hostname
                operator: In
                values:
                - "k8s-wk-1"
                - "k8s-wk-2"
                - "k8s-wk-3"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: lobby-paper-server
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: plugin-downloader
        image: minio/mc:RELEASE.2025-07-21T05-28-08Z-cpuv1
        env:
        - name: MINIO_ENDPOINT
          value: "minio-service-stg:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: root-user
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: root-password
        - name: BUCKET_NAME
          value: "plugins"
        - name: MC_CONFIG_DIR
          value: "/tmp/.mc"
        volumeMounts:
        - name: plugins-volume
          mountPath: /plugins
        - name: minio-config
          mountPath: /tmp/.mc
        command:
        - sh
        - -c
        - |
          echo "Downloading plugins from MinIO..."
          mkdir -p /plugins
          
          # Reset existing jar files in plugins directory
          echo "Resetting existing jar files..."
          rm -f /plugins/*.jar
          
          # Configure MinIO connection
          mc alias set minio http://${MINIO_ENDPOINT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}
          
          # List buckets to verify connection
          echo "Available buckets:"
          mc ls minio/
          
          # Download all plugins from bucket
          echo "Downloading from bucket: ${BUCKET_NAME}"
          mc cp --recursive minio/${BUCKET_NAME}/ /plugins/ || echo "No files in bucket or bucket not found"
          
          echo "Plugin download completed"
          ls -la /plugins
      containers:
      - name: paper
        env:
        - name: WHITELIST
          value: "naoido,kurazuuuuuu"
        - name: MEMORY
          value: "1G"
        - name: COPY_PLUGINS_SRC
          value: "/plugins"
        volumeMounts:
        - name: plugins-volume
          mountPath: /plugins
      volumes:
      - name: plugins-volume
        emptyDir: {}
      - name: minio-config
        emptyDir: {}