apiVersion: apps/v1
kind: Deployment
metadata:
  name: bungeecord-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bungeecord-proxy
  template:
    metadata:
      labels:
        app: bungeecord-proxy
    spec:
      containers:
      - name: bungeecord
        image: itzg/bungeecord
        ports:
        - containerPort: 25577
        volumeMounts:
        - name: config-volume
          mountPath: /config/config.yml
          subPath: bungeecord-config.yaml
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config.yaml
        - --loglevel
        - info
        - --protocol
        - http2
        - --no-autoupdate
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-token
              key: CLOUDFLARE_TUNNEL
        - name: NO_AUTOUPDATE
          value: "true"
        volumeMounts:
        - name: cloudflared-config
          mountPath: /etc/cloudflared
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: bungeecord-config
      - name: cloudflared-config
        configMap:
          name: cloudflared-config
---
apiVersion: v1
kind: Service
metadata:
  name: bungeecord-proxy-service
spec:
  selector:
    app: bungeecord-proxy
  ports:
  - name: bungeecord
    protocol: TCP
    port: 25577
    targetPort: 25577