apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby-paper-server
spec:
  template:
    spec:
      containers:
      - name: minio-sync
        image: minio/mc:latest-cpuv1
        env:
        - name: MINIO_ENDPOINT
          value: "MINIO_ENDPOINT_PLACEHOLDER"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: root-user
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: root-password
        - name: BUCKET_NAME
          value: "plugins"
        volumeMounts:
        - name: plugins-volume
          mountPath: /plugins
        - name: minio-config
          mountPath: /tmp/.mc
        command:
        - sh
        - -c
        - |
          echo "Starting MinIO bidirectional sync..."
          
          # Configure MinIO connection
          mc alias set minio http://${MINIO_ENDPOINT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}
          
          # Ensure bucket exists
          mc mb minio/${BUCKET_NAME} --ignore-existing
          
          # Create sync directories
          mkdir -p /plugins
          
          echo "Initial sync from MinIO to local..."
          mc mirror minio/${BUCKET_NAME}/ /plugins/ --overwrite
          
          echo "Starting continuous bidirectional sync..."
          while true; do
            # Sync from MinIO to local (downloads)
            echo "Syncing from MinIO to local..."
            mc mirror minio/${BUCKET_NAME}/ /plugins/ --overwrite --quiet || echo "Sync from MinIO failed"
            
            # Sync from local to MinIO (uploads)
            echo "Syncing from local to MinIO..."
            mc mirror /plugins/ minio/${BUCKET_NAME}/ --overwrite --quiet || echo "Sync to MinIO failed"
            
            # Wait before next sync cycle
            sleep 30
          done
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
      volumes:
      - name: minio-config
        emptyDir: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: survival-paper-server
spec:
  template:
    spec:
      containers:
      - name: minio-sync
        image: minio/mc:latest-cpuv1
        env:
        - name: MINIO_ENDPOINT
          value: "MINIO_ENDPOINT_PLACEHOLDER"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: root-user
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: root-password
        - name: BUCKET_NAME
          value: "plugins"
        volumeMounts:
        - name: plugins-volume
          mountPath: /plugins
        - name: minio-config
          mountPath: /tmp/.mc
        command:
        - sh
        - -c
        - |
          echo "Starting MinIO bidirectional sync..."
          
          # Configure MinIO connection
          mc alias set minio http://${MINIO_ENDPOINT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}
          
          # Ensure bucket exists
          mc mb minio/${BUCKET_NAME} --ignore-existing
          
          # Create sync directories
          mkdir -p /plugins
          
          echo "Initial sync from MinIO to local..."
          mc mirror minio/${BUCKET_NAME}/ /plugins/ --overwrite
          
          echo "Starting continuous bidirectional sync..."
          while true; do
            # Sync from MinIO to local (downloads)
            echo "Syncing from MinIO to local..."
            mc mirror minio/${BUCKET_NAME}/ /plugins/ --overwrite --quiet || echo "Sync from MinIO failed"
            
            # Sync from local to MinIO (uploads)
            echo "Syncing from local to MinIO..."
            mc mirror /plugins/ minio/${BUCKET_NAME}/ --overwrite --quiet || echo "Sync to MinIO failed"
            
            # Wait before next sync cycle
            sleep 30
          done
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
      volumes:
      - name: minio-config
        emptyDir: {}