apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby-paper-server
spec:
  serviceName: lobby-paper-server-service
  replicas: 1
  selector:
    matchLabels:
      app: lobby-paper-server
  template:
    metadata:
      labels:
        app: lobby-paper-server
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - name: paper
        image: itzg/minecraft-server
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        - name: ONLINE_MODE
          value: "FALSE"
        - name: TYPE
          value: "PAPER"
        - name: COPY_CONFIG_DEST
          value: "/data"
        - name: SYNC_SKIP_NEWER_IN_DESTINATION
          value: "false"
        - name: SKIP_SYMLINK_DIRS
          value: "true"
        - name: OPS
          value: "naoido, kurazuuuuuu"
        volumeMounts:
        - name: config-volume
          mountPath: /config/spigot.yml
          subPath: spigot.yml
        - name: data
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: paper-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: nfs-csi
---
apiVersion: v1
kind: Service
metadata:
  name: lobby-paper-server-service
spec:
  selector:
    app: lobby-paper-server
  ports:
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: 25565