apiVersion: apps/v1
kind: Deployment
metadata:
  name: survival-paper-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survival-paper-server
  template:
    metadata:
      labels:
        app: survival-paper-server
    spec:
      containers:
      - name: paper
        image: itzg/minecraft-server
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"
        volumeMounts:
        - name: config-volume
          mountPath: /config/paper-config.yml
          subPath: paper-config.yml
        - name: data
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: paper-config
      - name: data
        persistentVolumeClaim:
          claimName: survival-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: survival-paper-server-service
spec:
  selector:
    app: survival-paper-server
  ports:
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: survival-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-csi