apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
data:
  sshd_config: |
    Port 2222
    Protocol 2
    HostKey /etc/ssh/ssh_host_rsa_key
    HostKey /etc/ssh/ssh_host_ecdsa_key
    HostKey /etc/ssh/ssh_host_ed25519_key
    
    SyslogFacility AUTHPRIV
    LogLevel INFO
    
    LoginGraceTime 2m
    PermitRootLogin no
    StrictModes yes
    MaxAuthTries 6
    MaxSessions 10
    
    PubkeyAuthentication yes
    AuthorizedKeysFile /config/authorized_keys
    
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    KerberosAuthentication no
    GSSAPIAuthentication no
    
    UsePAM yes
    
    AllowAgentForwarding yes
    AllowTcpForwarding yes
    GatewayPorts no
    X11Forwarding no
    
    PrintMotd no
    PrintLastLog yes
    TCPKeepAlive yes
    
    AcceptEnv LANG LC_*
    
    Subsystem sftp /usr/libexec/openssh/sftp-server
    
  fetch_github_keys.sh: |
    #!/bin/bash
    set -e
    
    GITHUB_USERS="${GITHUB_USERS:-}"
    AUTHORIZED_KEYS_FILE="/config/authorized_keys"
    
    if [ -z "$GITHUB_USERS" ]; then
        echo "Error: GITHUB_USERS environment variable is not set"
        exit 1
    fi
    
    echo "Fetching GitHub public keys for users: $GITHUB_USERS"
    touch "$AUTHORIZED_KEYS_FILE"
    
    IFS=',' read -ra USERS <<< "$GITHUB_USERS"
    for user in "${USERS[@]}"; do
        user=$(echo "$user" | xargs)
        echo "Fetching keys for GitHub user: $user"
        
        if curl -sf "https://github.com/$user.keys" >> "$AUTHORIZED_KEYS_FILE"; then
            echo "" >> "$AUTHORIZED_KEYS_FILE"
        else
            echo "Warning: Failed to fetch keys for user $user"
        fi
    done
    
    if [ ! -s "$AUTHORIZED_KEYS_FILE" ]; then
        echo "Error: No keys were successfully fetched"
        exit 1
    fi
    
    chmod 600 "$AUTHORIZED_KEYS_FILE"
    
    echo "Successfully configured authorized_keys with $(wc -l < "$AUTHORIZED_KEYS_FILE") keys"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-github-users
data:
  GITHUB_USERS: "naoido,kurazuuuuuu"