apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby-paper-server
spec:
  template:
    spec:
      containers:
      - name: minio-sync
        env:
        - name: MINIO_ENDPOINT
          value: "minio-service-prd:9000"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: survival-paper-server
spec:
  template:
    spec:
      containers:
      - name: minio-sync
        env:
        - name: MINIO_ENDPOINT
          value: "minio-service-prd:9000"