apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby-paper-server
spec:
  template:
    spec:
      containers:
      - name: paper
        env:
        - name: MEMORY
          value: "5G"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: survival-paper-server
spec:
  template:
    spec:
      containers:
      - name: paper
        env:
        - name: MEMORY
          value: "5G"